{
 "title": "Availability",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "View Wishlist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "abur_view_metric_total{endpoint=\"wishlist\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "View Checkout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "abur_view_metric_total{endpoint=\"checkout\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "View Library",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "abur_view_metric_total{endpoint=\"library\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "View Store",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "abur_view_metric_total{endpoint=\"store\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "View Cart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "abur_view_metric_total{endpoint=\"cart\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}