{
 "title": "Performance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Store",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "hello_store_time_seconds_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "hello_cart_time_seconds_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Checkout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "hello_checkout_time_seconds_count{exception=\"none\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Library",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "hello_library_time_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wishlist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "hello_wishlist_time_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}