pipeline {

    agent any

    tools {
        jdk 'jdk21'
    }

    environment {
        DOCKER_CREDENTIALS = credentials("docker_password")
    }

    stages {
        stage('Build & Test') {
            steps {
                sh './gradlew clean build'
            }
        }

        stage('Push to Docker Hub') {
              steps {
                    script {
                        DOCKER_USERNAME = DOCKER_CREDENTIALS.username
                        DOCKER_PASSWORD = DOCKER_CREDENTIALS.password

                        GIT_TAG = sh([script: 'git fetch --tag && git tag', returnStdout: true]).trim()
                        MAJOR_VERSION = sh([script: 'git tag | cut -d . -f 1', returnStdout: true]).trim()
                        MINOR_VERSION = sh([script: 'git tag | cut -d . -f 2', returnStdout: true]).trim()
                        PATCH_VERSION = sh([script: 'git tag | cut -d . -f 3', returnStdout: true]).trim()

                        def NEW_MINOR = (MINOR_VERSION.toInteger() + 1).toString()
                        IMAGE_VERSION = "${MAJOR_VERSION}.${NEW_MINOR}.${PATCH_VERSION}"

                        sh """
                            docker build -t ${DOCKER_USERNAME}/hello-img:${IMAGE_VERSION} .
                            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} docker.io
                            docker push ${DOCKER_USERNAME}/hello-img:${IMAGE_VERSION}
                        """
                    }
              }
        }
    }

}
